FROM fedora:latest
ARG TARGETARCH
RUN echo $BUILDPLATFORM $TARGETPLATFORM $BUILDARCH $TARGETARCH

RUN dnf -y install gcc make git
RUN bash -c 'if [ "$TARGETARCH" == "arm64" ]; then dnf -y install gcc-aarch64-linux-gnu ; else dnf -y install gcc-x86_64-linux-gnu; fi'

RUN groupadd -r dev && useradd  -g dev -u 1000 dev
RUN mkdir -p /home/dev
RUN chown dev:dev /home/dev
# From here we run everything as dev user
USER       dev

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
ENV PATH="/home/dev/.cargo/bin:${PATH}"
RUN bash -c 'if [ "$TARGETARCH" == "arm64" ]; then rustup target install aarch64-unknown-linux-musl ; else rustup target install x86_64-unknown-linux-musl; fi'

ENV HOME /home/dev/
RUN mkdir $HOME/insights-runtime-extractor

CMD [ "/bin/bash" ]