apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: insights-runtime-extractor
  labels:
    app.kubernetes.io/name: insights-runtime-extractor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: insights-runtime-extractor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: insights-runtime-extractor
    spec:
      serviceAccountName: insights-runtime-extractor-sa
      hostPID: true
      # Deploy the insights-runtime-extractor only on Linux worker nodes
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: exporter
          image: ghcr.io/jmesnil/insights-runtime-exporter:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /data
              name: data-volume
          command:
            - /exporter
            - -bind
            - 0.0.0.0
        - name: extractor
          image: ghcr.io/jmesnil/insights-runtime-extractor:latest
          imagePullPolicy: Always
          env:
            - name: CONTAINER_RUNTIME_ENDPOINT
              value: unix:///crio.sock
          securityContext:
            privileged: true
            capabilities:
              drop:
                - ALL
              add:
                - CAP_SYS_ADMIN
          volumeMounts:
            - mountPath: /crio.sock
              name: crio-socket
            - mountPath: /data
              name: data-volume
      volumes:
        - name: crio-socket
          hostPath:
            path: /run/crio/crio.sock
            type: Socket
        - name: data-volume
          emptyDir: {}