name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the extractor
      run: |-
        cd ./extractor
        cargo fmt -- --check
        cargo build --release --verbose
        cargo test --release --verbose
    - name: Build the fingerprints
      run: |-
        cd ./fingerprints
        make test
    - name: Build the exporter
      run: |-
        cd ./exporter
        make test